[target.x86_64-pc-windows-msvc]
rustflags = [
  "-Clink-args=/OPT:REF,ICF",
  "-Zshare-generics=off",
  "-Zthreads=0",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=/usr/bin/mold", 
  "-Z", "share-generics=y",
  ]
